import { Geist, Geist_Mono, Josefin_Sans } from "next/font/google";
import "@/app/_styles/globals.css";

import Header from "./_components/Header";
import { ReservationProvider } from "./_components/ReservationContext";


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });
const josefinSans = Josefin_Sans({
  subsets: ["latin"],
  display: "swap",
})
// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title:{
    default: "The Wild Oasis",
    template: "%s | The Wild Oasis"
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children}) {
  // const {slug ='/dasboard'} = params||{}
  // console.log(slug);
  // const isDashboard = slug ? true : false;
  // console.log(isDashboard);

 
  return (
    <html lang="en">
      <body
        className={`${josefinSans.className} antialiased bg-primary-800 text-primary-100 min-h-screen flex flex-col relative` }
      >
       <Header/>
       <div className="flex-1 px-8 py-12 grid  ">
       <main className="max-w-7xl mx-auto w-full ">
        <ReservationProvider>
        {children}
        </ReservationProvider>
     
        </main>
       </div>
      
      </body>
    </html>
  );
}
